/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_acz_leveldb_LevelDbNative */

#ifndef _Included_org_acz_leveldb_LevelDbNative
#define _Included_org_acz_leveldb_LevelDbNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_acz_leveldb_LevelDbNative
 * Method:    open0
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_acz_leveldb_LevelDbNative_open0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_acz_leveldb_LevelDbNative
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_acz_leveldb_LevelDbNative_close0
  (JNIEnv *, jobject);

/*
 * Class:     org_acz_leveldb_LevelDbNative
 * Method:    get0
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_acz_leveldb_LevelDbNative_get0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_acz_leveldb_LevelDbNative
 * Method:    put0
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_acz_leveldb_LevelDbNative_put0
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_acz_leveldb_LevelDbNative
 * Method:    delete0
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_acz_leveldb_LevelDbNative_delete0
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
